<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDnclyrn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDnclyrn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDnclyrn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDnclyrn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDnclyrn\appProdProjectContainer([
    'container.build_hash' => 'Dnclyrn',
    'container.build_id' => '06b0bf58',
    'container.build_time' => 1601067402,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDnclyrn');
